title: NTU Exchange Resources
description: Resources, links, and maps for Nanyang Technological University (NTU) international exchange students to traverse the webs of bureaucracy and enjoy your time at NTU.
theme: jekyll-theme-slate
